name: Assets
on:
  release:
    types: [published]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        GOOS: [linux, darwin]
        GOARCH: [amd64, arm64]
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.GOOS }}
      GOARCH: ${{ matrix.GOARCH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup environment
        id: env
        run: |
          if [[ "${{ github.event.release.tag_name }}" == "" ]]; then
            tag=$(git rev-parse --short HEAD)
          else
            tag=${{ github.event.release.tag_name }}
          fi
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Build binaries
        run: |
          make build BINARY=broadcaster-${{ steps.env.outputs.tag }}-$GOOS-$GOARCH

      - name: Upload Release Assets
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.env.outputs.tag }} \
            ./bin/broadcaster-${{ steps.env.outputs.tag }}-$GOOS-$GOARCH \
            --clobber
