name: Build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth in GC
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GC_SERVICE_ACCOUNT }}"

      - name: Setup GC SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker auth
        run: |
          gcloud info
          gcloud auth configure-docker ${{ vars.GC_REGION }}-docker.pkg.dev --quiet

      - name: Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: "${{ vars.GC_REGION }}-docker.pkg.dev/${{ secrets.GC_PROJECT }}/a0feed"
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
