name: Image
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - .github/dependabot.yml
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - README.md
      - LICENSE
      - .github/dependabot.yml
jobs:
  gh:
    name: Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,enable=true,prefix=,format=long

      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}

  # gc:
  #   name: Google Clooud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup GC SDK
  #       uses: google-github-actions/setup-gcloud@v1

  #     - name: Metadata
  #       id: metadata
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: |
  #           ${{ vars.GC_REGION }}-docker.pkg.dev/${{ secrets.GC_PROJECT }}/${{ github.repository }}
  #         tags: |
  #           type=raw,value=latest,enable={{is_default_branch}}
  #           type=sha,enable=true,prefix=,format=long

  #     - name: Auth in GC
  #       if: github.event_name != 'pull_request'
  #       id: auth
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: "${{ secrets.GC_SERVICE_ACCOUNT }}"

  #     - name: Docker auth
  #       if: github.event_name != 'pull_request'
  #       run: |
  #         gcloud info
  #         gcloud auth configure-docker ${{ vars.GC_REGION }}-docker.pkg.dev --quiet

  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: ${{ github.event_name != 'pull_request' }}
  #         labels: ${{ steps.metadata.outputs.labels }}
  #         tags: ${{ steps.metadata.outputs.tags }}
