name: Image
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.metadata.outputs.tags }}
      labels: ${{ steps.metadata.outputs.labels }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            ${{ vars.GC_REGION }}-docker.pkg.dev/${{ secrets.GC_PROJECT }}/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,enable=true,prefix=,format=long

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
          outputs: type=docker,dest=/tmp/images.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: /tmp/images.tar
          retention-days: 1

  upload_gc:
    runs-on: ubuntu-latest
    needs: [build]
    # if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: images
          path: /tmp

      - name: Load images
        run: |
          docker load --input /tmp/images.tar
          docker image ls -a

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GC SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Auth in GC
        if: github.event_name != 'pull_request'
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GC_SERVICE_ACCOUNT }}"

      - name: Docker auth
        run: |
          gcloud info
          gcloud auth configure-docker ${{ vars.GC_REGION }}-docker.pkg.dev --quiet

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # FIXME
          tags: |
            ${{ vars.GC_REGION }}-docker.pkg.dev/${{ secrets.GC_PROJECT }}/${{ github.repository }}:${{ github.sha }}
          labels: ${{ needs.build.outputs.labels }}

  upload_gh:
    runs-on: ubuntu-latest
    needs: [build]
    # if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: images
          path: /tmp

      - name: Load images
        run: |
          docker load --input /tmp/images.tar
          docker image ls -a

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # FIXME
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          labels: ${{ needs.build.outputs.labels }}
